import type { Metadata } from "next";
import { Oxanium } from 'next/font/google';
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const oxanium = Oxanium({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-oxanium',
});

export const metadata: Metadata = {
  title: "Hafiizh Herdian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${oxanium.variable} font-sans antialiased flex flex-col min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors duration-200`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Navbar global */}
          <Header />

          {/* Konten halaman fleksibel */}
          <main className="flex-grow">{children}</main>

          {/* Footer global */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
